import Link from "next/link";
import { business } from "../../config/business";

const sections = [
  { title: "Popular", items: [["Chicken Tikka", "£4.95", "Chargrilled tikka pieces."], ["Pasanda", "£7.95", "Mild, creamy, with almonds and coconut."], ["Jalfry", "£7.95", "Hot and exotic with onions and green peppers."], ["Butter", "£7.95", "Mild, creamy and comforting."], ["Madras", "£7.95", "A classic with a proper kick."], ["Biryani", "£7.95", "Fragrant rice mixed with your chosen style."]]},
  { title: "Starters", items: [["Chicken Tikka", "£4.95", "A crowd-pleasing tandoori favourite."], ["Sheek Kebab", "Ask", "Seasoned minced meat, cooked over high heat."], ["Vegetable Samosa", "Ask", "Crisp pastry with a spiced vegetable filling."], ["Onion Bhaji", "Ask", "Crisp, spiced onion fritters."]]},
  { title: "Main dishes", items: [["Korma", "£7.95", "Mild and creamy."], ["Masala", "£7.95", "Mild, creamy with almonds and coconut."], ["Dansak", "£7.95", "Medium spicy, sweet and sour lentil sauce."], ["Rogan Josh", "Ask", "Rich, aromatic and warming."], ["Jalfrezi", "£7.95", "Hot, fresh and packed with peppers and onions."]]},
  { title: "Sides & rice", items: [["Pilaw Rice", "£3.50", "Fragrant basmati rice."], ["Naan", "Ask", "Freshly baked Indian flatbread."], ["Side dishes", "Ask", "A range of vegetable and classic sides."]]},
];

export default function MenuPage() {
  return <main className="min-h-screen bg-[#100d0a] text-[#fff8ec]">
    <nav className="sticky top-0 z-50 border-b border-white/10 bg-[#100d0a]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-10"><Link href="/" className="text-xl font-semibold">Sultan <span className="text-orange-400">To Go</span></Link><div className="hidden gap-7 text-sm text-white/60 md:flex"><Link href="/menu" className="text-white">Menu</Link><Link href="/about">Our story</Link><Link href="/offers">Offers</Link><Link href="/contact">Contact</Link></div><a href={business.bookingUrl} target="_blank" rel="noreferrer" className="rounded-full bg-orange-400 px-5 py-2.5 text-sm font-semibold text-black">Order now</a></div></nav>
    <header className="mx-auto max-w-7xl px-5 pb-20 pt-24 lg:px-10"><p className="text-xs uppercase tracking-[.4em] text-orange-400">The menu</p><h1 className="mt-5 text-6xl font-semibold tracking-[-.07em] sm:text-8xl">Choose your<br/><span className="text-orange-400">favourite.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/45">A demo presentation based on publicly listed menu information. Prices and availability should be confirmed with the business before launch.</p></header>
    <section className="mx-auto max-w-7xl space-y-5 px-5 pb-28 lg:px-10">{sections.map(section=><div key={section.title} className="rounded-[2rem] border border-white/10 bg-white/[.025] p-6 sm:p-9"><div className="mb-8 flex items-end justify-between border-b border-white/10 pb-5"><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">{section.title}</h2><span className="text-xs uppercase tracking-[.25em] text-white/25">Sultan</span></div><div className="grid gap-x-10 sm:grid-cols-2">{section.items.map(([name,price,description])=><article key={name} className="border-b border-white/10 py-5 last:border-0"><div className="flex justify-between gap-5"><h3 className="font-medium">{name}</h3><span className="shrink-0 text-orange-400">{price}</span></div><p className="mt-2 text-sm leading-6 text-white/35">{description}</p></article>)}</div></div>)}</section>
    <section className="bg-orange-400 px-5 py-16 text-black lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 md:flex-row md:items-center"><div><p className="text-xs uppercase tracking-[.35em] text-black/60">Ready?</p><h2 className="mt-2 text-4xl font-semibold tracking-tight">Order your favourites.</h2></div><a href={business.bookingUrl} target="_blank" rel="noreferrer" className="rounded-full bg-black px-7 py-4 text-center font-semibold text-white">Order online ↗</a></div></section>
  </main>;
}
