import Link from "next/link";
import { business } from "../../config/business";

const sections = [
  { title: "Most popular", items: [["Chicken Tikka", "£4.95", ""], ["Pilaw Rice", "£3.50", ""], ["Pasanda", "£7.95", "Mild, with red wine, fresh cream, almonds and coconut."], ["Jalfry", "£7.95", "Hot and exotic with onions and green peppers."], ["Butter", "£7.95", "Mild, cooked with coconut and cream."], ["Madras", "£7.95", "Hot."], ["Biryani", "£7.95", "Mixed with rice."], ["Dansak", "£7.95", "Medium spicy, sweet and sour lentil sauce."], ["Korma", "£7.95", "Mild and creamy."], ["Masala", "£7.95", "Mild, creamy with almonds and coconut."]]},
  { title: "Starters", items: [["Papadom", "£0.95", ""], ["Spicy Papadom", "£0.95", ""], ["Onion Bhajee", "£3.95", ""], ["Chicken Tikka", "£4.95", ""], ["Lamb Tikka", "£4.95", ""], ["Tandoori King Prawn", "£6.95", ""], ["Sheek Kebab", "£4.95", ""], ["Tikka Platter", "£5.50", "Chicken tikka, lamb tikka, sheek kebab and onion bhajee."], ["Meat Samosas", "£3.50", ""], ["Vegetable Samosas", "£3.50", "Vegetarian."], ["Chicken Chaat Puri", "£4.50", ""], ["King Prawn Puri", "£5.50", ""], ["Tiger Prawn Puri", "£5.50", ""]]},
  { title: "Main dishes", items: [["Korma", "£7.95", "Mild and creamy."], ["Masala", "£7.95", "Mild, creamy with almonds and coconut."], ["Pasanda", "£7.95", "Mild, with red wine, fresh cream, almonds and coconut."], ["Butter", "£7.95", "Mild, cooked with coconut and cream."], ["Curry", "£7.95", "Medium spicy."], ["Bhuna", "£7.95", "Slightly dry, medium spicy."], ["Garlic Bhuna", "£7.95", "Slightly dry, medium spicy."], ["Saag", "£7.95", "Medium spicy with spinach."], ["Dupiaza", "£7.95", "Medium spicy with onions."], ["Dansak", "£7.95", "Medium spicy, sweet and sour lentil sauce."], ["Balti", "£7.95", "Slightly dry, medium spicy with onions and green peppers."], ["Korai", "£7.95", "Slightly dry, medium spicy with onions and green peppers."], ["Rogon", "£7.95", "Medium spicy with tomatoes."], ["Rezala", "£7.95", "Medium spicy, slightly dry with mince meat."], ["Biryani", "£7.95", "Mixed with rice."], ["Pathia", "£7.95", "Medium hot, sweet and sour."], ["Jalfry", "£7.95", "Hot and exotic with onions and green peppers."], ["Madras", "£7.95", "Hot."], ["Garlic Chilli", "£7.95", "Hot."], ["Chilli Masala", "£7.95", "Hot."], ["Vindaloo", "£7.95", "Very hot."], ["Kabull Lamb", "£9.50", "Lamb cooked with chickpeas in a medium spiced onion and tomato bhuna sauce."], ["Chilli Naga Special", "£10.00", "Chicken, lamb, vegetables or prawns cooked in Madras sauce with Bangladeshi hot pepper pickle."], ["Grandma's Deal", "£8.95", "Fresh vegetables including spinach, lentils and chickpeas, cooked in a medium spiced sauce."], ["Balti Chilli Naga", "£10.95", "Traditional balti infused with naga chilli pickle (madras hot)."]]},
  { title: "Tandoori dishes", items: [["Chicken Tikka", "£9.95", ""], ["Lamb Tikka", "£9.95", ""], ["Tandoori King Prawn", "£12.95", ""], ["Tandoori Mixed Grill Special", "£10.95", "Chicken tikka, lamb tikka, sheek kebab and naan."], ["Chicken Shashlik", "£10.95", ""], ["Lamb Shashlik", "£11.95", ""]]},
  { title: "Side dishes", items: [["Vegetable Curry", "£3.95", "Vegetarian."], ["Vegetable Bhajee", "£3.95", "Vegetarian."], ["Mushroom Bhajee", "£3.95", ""], ["Bombay Aloo", "£3.95", ""], ["Saag Aloo", "£3.95", ""], ["Saag Bhajee", "£3.95", ""], ["Saag Paneer", "£3.95", ""], ["Tarka Dall", "£3.95", ""], ["Chana Masala", "£3.95", ""], ["Mushroom Aloo", "£3.95", ""], ["Saag Mushroom", "£3.95", ""], ["Garlic Mushroom", "£3.95", ""], ["Muttor Paneer", "£3.95", ""], ["Aloo Muttor", "£3.95", ""], ["Gobi Bhajee", "£3.95", ""], ["Aloo Gobi", "£3.95", ""]]},
  { title: "Rice", items: [["Plain Rice", "£3.50", "Basmati."], ["Pilaw Rice", "£3.50", ""], ["Mushroom Fried Rice", "£3.95", ""], ["Special Fried Rice", "£3.95", "Peas, prawns and egg."], ["Egg Fried Rice", "£3.95", ""], ["Coconut Rice", "£3.95", ""], ["Keema Rice", "£3.95", ""], ["Vegetable Rice", "£3.95", "Vegetarian."], ["Garlic Fried Rice", "£3.95", ""]]},
  { title: "Breads", items: [["Naan", "£3.50", ""], ["Peshwari Naan", "£3.50", ""], ["Garlic Naan", "£3.50", ""], ["Vegetable Naan", "£3.50", "Vegetarian."], ["Chilli Naan", "£3.50", ""], ["Keema Naan", "£3.50", ""], ["Chilli Keema Naan", "£3.50", ""]]},
  { title: "Extras", items: [["Mint Sauce", "£0.95", ""], ["Mango Chutney", "£0.95", ""], ["Lime Pickle", "£0.95", ""], ["Onion Salad", "£0.95", ""]]},
  { title: "Drinks", items: [["Coke 0.33l", "£2.25", ""], ["Diet Coke 0.33l", "£2.25", ""], ["Sprite 0.33l", "£2.25", ""], ["Fanta 0.33l", "£2.25", ""], ["Coke 1.5l", "£3.50", ""], ["Diet Coke 1.5l", "£3.50", ""]]},
];

export default function MenuPage() {
  return <main className="min-h-screen bg-[#100d0a] text-[#fff8ec]">
    <nav className="sticky top-0 z-50 border-b border-white/10 bg-[#100d0a]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-10"><Link href="/" className="text-xl font-semibold">Sultan <span className="text-orange-400">To Go</span></Link><div className="hidden gap-7 text-sm text-white/60 md:flex"><Link href="/menu" className="text-white">Menu</Link><Link href="/about">Our story</Link><Link href="/offers">Offers</Link><Link href="/contact">Contact</Link></div><a href={business.bookingUrl} target="_blank" rel="noreferrer" className="rounded-full bg-orange-400 px-5 py-2.5 text-sm font-semibold text-black">Order now</a></div></nav>
    <header className="mx-auto max-w-7xl px-5 pb-20 pt-24 lg:px-10"><p className="text-xs uppercase tracking-[.4em] text-orange-400">The menu</p><h1 className="mt-5 text-6xl font-semibold tracking-[-.07em] sm:text-8xl">The real<br/><span className="text-orange-400">Sultan menu.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/45">Menu items and prices shown here are taken from Sultan To Go's publicly listed online menu. Prices and availability can change, so the live ordering site remains the source of truth.</p></header>
    <section className="mx-auto max-w-7xl space-y-5 px-5 pb-28 lg:px-10">{sections.map(section=><div key={section.title} className="rounded-[2rem] border border-white/10 bg-white/[.025] p-6 sm:p-9"><div className="mb-8 flex items-end justify-between border-b border-white/10 pb-5"><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">{section.title}</h2><span className="text-xs uppercase tracking-[.25em] text-white/25">Sultan To Go</span></div><div className="grid gap-x-10 sm:grid-cols-2">{section.items.map(([name,price,description])=><article key={name} className="border-b border-white/10 py-5 last:border-0"><div className="flex justify-between gap-5"><h3 className="font-medium">{name}</h3><span className="shrink-0 text-orange-400">{price}</span></div>{description && <p className="mt-2 text-sm leading-6 text-white/35">{description}</p>}</article>)}</div></div>)}</section>
    <section className="bg-orange-400 px-5 py-16 text-black lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 md:flex-row md:items-center"><div><p className="text-xs uppercase tracking-[.35em] text-black/60">Ready?</p><h2 className="mt-2 text-4xl font-semibold tracking-tight">Order your favourites.</h2><p className="mt-2 max-w-xl text-sm text-black/60">Order online through Sultan To Go's existing ordering service.</p></div><a href={business.bookingUrl} target="_blank" rel="noreferrer" className="rounded-full bg-black px-7 py-4 text-center font-semibold text-white">Order online ↗</a></div></section>
  </main>;
}
