"use client";

import { useMemo, useState } from "react";
import { business } from "../config/business";

const services = [
  { id: "carpet", no: "01", title: "Carpets & upholstery", text: "Bring carpets, rugs, upholstery and floor surfaces back to a cleaner, fresher finish." },
  { id: "office", no: "02", title: "Office cleaning", text: "Regular or one-off commercial cleaning planned around the hours your business actually works." },
  { id: "driveway", no: "03", title: "Driveways & patios", text: "Outdoor surfaces cleaned with modern equipment, including paving, paths, patios and walkways." },
  { id: "outdoor", no: "04", title: "Fascias, gutters & more", text: "A wider outdoor clean-up covering conservatories, fascia, guttering and other exterior surfaces." },
];

const areas = ["Eastbourne", "Polegate", "Pevensey", "Westham", "Hailsham", "Seaford", "Bexhill", "East Sussex"];

export default function Home() {
  const [service, setService] = useState("carpet");
  const [property, setProperty] = useState("Home");
  const [size, setSize] = useState("Standard");
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const selected = services.find((item) => item.id === service) ?? services[0];

  const enquiry = useMemo(() => {
    const subject = `Cleaning enquiry — ${selected.title}`;
    const body = `Hello Select Cleaning Services,\n\nI'd like to ask about ${selected.title.toLowerCase()}.\nProperty: ${property}\nApprox. size: ${size}\nArea: Eastbourne / East Sussex\n\nPlease let me know what information you need for an estimate.\n\nThanks`;
    return `mailto:${business.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  }, [property, selected, size]);

  const ask = () => {
    const q = question.toLowerCase();
    if (!q) return setAnswer("Ask about carpets, offices, driveways, outdoor cleaning, areas covered or estimates.");
    if (q.includes("carpet") || q.includes("sofa") || q.includes("upholstery")) return setAnswer("Select Cleaning Services specialises in carpet cleaning and can also clean rugs, upholstery and floor tiles. The team says a spot check is carried out before carpet work to help avoid marking, bleaching or staining.");
    if (q.includes("office") || q.includes("commercial")) return setAnswer("Office and commercial cleaning is available for businesses and property management clients, including weekly or monthly contract cleaning and end-of-tenancy requirements.");
    if (q.includes("drive") || q.includes("patio") || q.includes("path")) return setAnswer("Driveways, paths, walkways and patios are among the outdoor services offered. The business also describes block-paving restoration, weed treatment, re-sanding, stain removal and sealant as available where required.");
    if (q.includes("area") || q.includes("where") || q.includes("hailsham") || q.includes("bexhill")) return setAnswer("The published coverage includes Eastbourne, Bexhill, Hailsham, Seaford, Westham, Pevensey, Polegate and wider East Sussex.");
    if (q.includes("price") || q.includes("cost") || q.includes("quote") || q.includes("estimate")) return setAnswer("The business invites customers to request a free, no-obligation estimate. This site deliberately does not invent fixed prices because the published information doesn't provide a price list.");
    if (q.includes("experience") || q.includes("family")) return setAnswer("Select Cleaning Services describes itself as a family-run business with more than 20 years of experience.");
    return setAnswer("I can answer from the public business information used for this demo. Try asking about carpets, offices, driveways, outdoor cleaning, coverage or estimates.");
  };

  return (
    <main className="min-h-screen bg-[#f7f7f4] text-[#111318] selection:bg-[#145cff] selection:text-white">
      <header className="border-b border-[#111318]/10 px-5 py-5 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-[1500px] items-center justify-between"><a href="#top" className="flex items-center gap-3 text-sm font-black uppercase tracking-[-.03em]"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#145cff] text-white">S</span> Select Cleaning</a><nav className="hidden gap-8 text-sm font-semibold md:flex"><a href="#services">Services</a><a href="#coverage">Coverage</a><a href="#planner">Get an estimate</a></nav><a href={`tel:${business.phone.replaceAll(" ", "")}`} className="rounded-full bg-[#111318] px-5 py-3 text-xs font-bold text-white">Call us ↗</a></div></header>

      <section id="top" className="px-5 pb-10 pt-5 sm:px-8 lg:px-12"><div className="mx-auto grid max-w-[1500px] overflow-hidden rounded-[2rem] bg-[#145cff] text-white lg:grid-cols-[1.25fr_.75fr]"><div className="relative min-h-[650px] p-7 sm:p-12 lg:p-16"><div className="absolute right-[-10%] top-[-10%] h-[65vw] w-[65vw] max-h-[720px] max-w-[720px] rounded-full border-[100px] border-white/[.08]"/><div className="relative flex h-full flex-col justify-between"><div><p className="mb-8 text-xs font-bold uppercase tracking-[.35em] text-white/60">Eastbourne · East Sussex</p><h1 className="max-w-5xl text-[17vw] font-black uppercase leading-[.78] tracking-[-.09em] sm:text-8xl lg:text-[9rem]">Clean<br/><span className="text-[#c9ff3d]">properly.</span></h1></div><div className="grid gap-8 pt-16 sm:grid-cols-[1fr_250px]"><p className="max-w-xl text-lg leading-8 text-white/75">Carpets, offices, driveways and outdoor surfaces — one local team, more than 20 years of experience.</p><div className="border-l border-white/20 pl-6 text-xs font-bold uppercase leading-6 tracking-[.15em] text-white/55">Family run<br/>Eastbourne based<br/>East Sussex coverage</div></div></div></div><div className="relative min-h-[500px] overflow-hidden bg-[#c9ff3d] p-7 text-[#111318] sm:p-12 lg:p-10"><div className="absolute inset-x-0 bottom-0 h-[44%] bg-[#f7f7f4]"/><div className="relative flex h-full flex-col justify-between"><div className="flex justify-between text-xs font-bold uppercase tracking-[.25em]"><span>SELECT / 01</span><span>20+ years</span></div><div className="relative"><p className="text-6xl font-black uppercase leading-[.82] tracking-[-.07em]">Fresh<br/>space.<br/><span className="text-[#145cff]">Fast.</span></p><div className="mt-8 grid max-w-xs grid-cols-2 gap-2 text-xs font-bold uppercase"><span className="rounded-full border border-[#111318]/20 px-4 py-2">Home</span><span className="rounded-full border border-[#111318]/20 px-4 py-2">Office</span><span className="rounded-full border border-[#111318]/20 px-4 py-2">Outside</span><span className="rounded-full border border-[#111318]/20 px-4 py-2">Vehicle</span></div></div><a href="#planner" className="relative block rounded-full bg-[#111318] px-6 py-4 text-center text-sm font-bold text-white">Build my cleaning brief →</a></div></div></div></section>

      <section id="services" className="px-5 py-24 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1500px]"><div className="grid gap-8 lg:grid-cols-[1fr_350px]"><div><p className="text-xs font-black uppercase tracking-[.35em] text-[#145cff]">The clean list</p><h2 className="mt-5 text-6xl font-black uppercase leading-[.82] tracking-[-.08em] sm:text-8xl">One team.<br/><span className="text-[#145cff]">Many surfaces.</span></h2></div><p className="self-end text-sm leading-7 text-black/50">From a carpet that needs rescuing to an office that needs a regular routine, the service can be shaped around the job.</p></div><div className="mt-16 border-t-2 border-[#111318]">{services.map((item)=><button key={item.id} onClick={()=>setService(item.id)} className={`grid w-full gap-5 border-b border-[#111318]/15 py-8 text-left transition md:grid-cols-[70px_1fr_1fr_80px] md:items-center ${service===item.id?"bg-[#c9ff3d] px-5":"px-0"}`}><span className="text-sm font-black text-[#145cff]">{item.no}</span><span className="text-2xl font-black uppercase tracking-[-.04em] sm:text-4xl">{item.title}</span><span className="max-w-lg text-sm leading-6 text-black/45">{item.text}</span><span className="text-right text-2xl">↗</span></button>)}</div></div></section>

      <section id="planner" className="bg-[#111318] px-5 py-24 text-white sm:px-8 lg:px-12"><div className="mx-auto max-w-[1500px]"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-black uppercase tracking-[.35em] text-[#c9ff3d]">Cleaning brief</p><h2 className="mt-5 text-6xl font-black uppercase leading-[.82] tracking-[-.08em] sm:text-8xl">Tell us<br/><span className="text-[#c9ff3d]">what needs</span><br/>cleaning.</h2><p className="mt-7 max-w-md text-sm leading-7 text-white/40">No price calculator pretending to know the job. Build a useful brief instead, then send it to the team for a proper estimate.</p></div><div className="rounded-[2rem] bg-[#f7f7f4] p-6 text-[#111318] sm:p-9"><div className="grid gap-8"><div><p className="text-xs font-black uppercase tracking-[.25em] text-black/35">01 · Service</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{services.map(item=><button key={item.id} onClick={()=>setService(item.id)} className={`rounded-xl border p-4 text-left text-sm font-bold ${service===item.id?"border-[#145cff] bg-[#145cff] text-white":"border-black/10"}`}>{item.title}</button>)}</div></div><div><p className="text-xs font-black uppercase tracking-[.25em] text-black/35">02 · Property</p><div className="mt-4 flex flex-wrap gap-2">{["Home","Office / commercial","Rental property","Outdoor space","Vehicle"].map(item=><button key={item} onClick={()=>setProperty(item)} className={`rounded-full border px-4 py-2 text-sm font-semibold ${property===item?"border-[#111318] bg-[#111318] text-white":"border-black/10"}`}>{item}</button>)}</div></div><div><p className="text-xs font-black uppercase tracking-[.25em] text-black/35">03 · Approx. size</p><div className="mt-4 flex flex-wrap gap-2">{["Small","Standard","Large","Not sure"].map(item=><button key={item} onClick={()=>setSize(item)} className={`rounded-full border px-4 py-2 text-sm font-semibold ${size===item?"border-[#145cff] bg-[#145cff] text-white":"border-black/10"}`}>{item}</button>)}</div></div><div className="rounded-2xl bg-[#c9ff3d] p-5"><p className="text-xs font-black uppercase tracking-[.2em] text-black/40">Ready to send</p><p className="mt-2 text-2xl font-black uppercase">{selected.title}</p><p className="mt-1 text-sm text-black/55">{property} · {size} · Eastbourne / East Sussex</p><a href={enquiry} className="mt-5 block rounded-full bg-[#111318] px-5 py-3 text-center text-sm font-bold text-white">Request a free estimate →</a></div></div></div></div></div></section>

      <section id="coverage" className="bg-[#c9ff3d] px-5 py-24 text-[#111318] sm:px-8 lg:px-12"><div className="mx-auto max-w-[1500px]"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-black uppercase tracking-[.35em]">Where we work</p><h2 className="mt-5 text-6xl font-black uppercase leading-[.82] tracking-[-.08em] sm:text-8xl">Local<br/><span className="text-[#145cff]">by design.</span></h2></div><div className="grid grid-cols-2 gap-px border border-black/15 bg-black/15 sm:grid-cols-4">{areas.map(area=><div key={area} className="bg-[#c9ff3d] p-6 text-lg font-black uppercase">{area}<span className="mt-8 block text-sm font-normal opacity-40">↗</span></div>)}</div></div></div></section>

      <section className="bg-[#f7f7f4] px-5 py-24 sm:px-8 lg:px-12"><div className="mx-auto max-w-4xl"><p className="text-xs font-black uppercase tracking-[.35em] text-[#145cff]">Ask the site</p><h2 className="mt-4 text-5xl font-black uppercase leading-[.9] tracking-[-.06em] sm:text-6xl">Before you<br/>pick up the phone.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-black/45">A small grounded assistant using the researched business information. It won't invent prices or availability.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Do you clean offices?" className="min-w-0 flex-1 rounded-xl border border-black/10 bg-white px-4 py-3 text-sm outline-none focus:border-[#145cff]"/><button onClick={ask} className="rounded-xl bg-[#145cff] px-6 py-3 text-sm font-bold text-white">Ask</button></div>{answer&&<div className="mt-4 rounded-xl border border-[#145cff]/15 bg-[#145cff]/5 p-5 text-sm leading-7"><span className="font-bold text-[#145cff]">Answer · </span>{answer}</div>}</div></section>

      <footer className="bg-[#111318] px-5 py-12 text-white sm:px-8 lg:px-12"><div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-8 border-b border-white/10 pb-10 sm:flex-row"><div><p className="text-2xl font-black uppercase">Select Cleaning</p><p className="mt-2 text-sm text-white/35">Family-run cleaning across Eastbourne & East Sussex.</p></div><div className="text-sm leading-7 text-white/45"><a className="block text-[#c9ff3d]" href={`tel:${business.phone.replaceAll(" ", "")}`}>{business.phone}</a><a className="block text-[#c9ff3d]" href={`mailto:${business.email}`}>{business.email}</a></div></div><div className="pt-6 text-xs uppercase tracking-[.2em] text-white/20">© 2026 Select Cleaning Services · Eastbourne · East Sussex</div></div></footer>
    </main>
  );
}
